nodeLinker: node-modules

npmScopes:
  emogit:
    npmRegistryServer: https://npm.pkg.github.com/
    npmAlwaysAuth: false
    npmAuthToken: ${EMOGIT_NPM_AUTH_TOKEN-notset}

yarnPath: ../.yarn/releases/yarn-3.1.1.cjs

# Resolve an issue with babel not working with create-react-app.
# https://github.com/facebook/create-react-app/issues/11793#issuecomment-998230832
packageExtensions:
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"