nodeLinker: node-modules
npmPublishAccess: public
npmPublishRegistry: "https://npm.pkg.github.com"

npmScopes:
  emogit:
    npmAlwaysAuth: false
    npmAuthToken: "${EMOGIT_NPM_AUTH_TOKEN-notset}"
    npmRegistryServer: "https://npm.pkg.github.com/"

# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#     spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
