nodeLinker: node-modules
yarnPath: ../.yarn/releases/yarn-3.1.1.cjs

npmScopes:
  emogit:
    npmRegistryServer: https://npm.pkg.github.com/
    npmAlwaysAuth: false
    npmAuthToken: ${EMOGIT_NPM_AUTH_TOKEN-notset}