name: Build

on:
  push:
    branches:
    - main
    - use-emojit-core
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  core:
    name: Core
    runs-on: ubuntu-latest
    defaults:
      run:
        # Directory for run steps.
        working-directory: core

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: "Install"
        run: |
          set -ex
          yarn install
        env:
          EMOGIT_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build"
        run: |
          set -ex
          yarn build
        # env:
        #   EMOGIT_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish"
        if: github.ref == 'refs/heads/master'
        run: |
          set -ex
          yarn npm publish
        env:
          # NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMOGIT_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  extension:
    name: Extension
    needs: core
    # Change to ubuntu-20.04 when it is fully supported.
    runs-on: ubuntu-latest
    defaults:
      run:
        # Directory for run steps.
        working-directory: extension

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
        env:
          EMOGIT_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: yarn test

      - name: Lint
        # Split Lint into a separate task so that it can always run even if the tests fail.
        run: yarn lint
        if: success() || failure()

      - name: Build
        run: yarn build chrome
